#!/bin/bash
 
PATHNUM=$(echo $0 | awk '{print gsub(/\..\//, "")}') 
DIRPATH='' 

if [ $PATHNUM -gt 0 ];
then
  for ((i=0; i<$PATHNUM; i++));
  do
    DIRPATH="${DIRPATH}../"
  done
fi

DIRPATH="${DIRPATH}scripts/randomStudents.js"

node $DIRPATH
